language: python

python:
  - 2.7
  - 3.5

services: postgresql

env:
  - DJANGO=1.9.8

before_install:
  - export PYTHONPATH=$HOME/builds/swappsco/django-email
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements_test.txt

script:
  - python runtests.py
